#include "prosystem.h"
#include "multisprite.h"

// Generated by sprites7800 bombjack_tiles.yaml 
#include "example_bombjack_tiles.c"

// Generated by tiles7800 --sparse bombjack_tiles.yaml bombjack_sphinx.tmx
#include "example_bombjack_sphinx.c"

void main()
{
    multisprite_init();
    multisprite_set_charbase(sky);
    multisprite_sparse_tiling(tilemap_sphinx_data_ptrs, 0, 16, 14);
    multisprite_save();
    
    // Blue palette
    *P4C1 = multisprite_color(0x84); // Dark blue 
    *P4C2 = multisprite_color(0x87); // Light blue
    *P4C3 = multisprite_color(0xac); // Turquoise 
    
    // Sphinx palette
    *P5C1 = multisprite_color(0x43); // Red
    *P5C2 = multisprite_color(0x37); // Orange
    *P5C3 = multisprite_color(0x1c); // Yellow 

    // Main loop
    do {
        multisprite_flip();
    } while(1);
}
