bank1 char dobkeratops_ram[4096]; // Should be at 0x7000 after VRAM (12kB at 0x4000)

// Generated by sprites7800 dobkeratops.yaml
#include "example_dobkeratops_gfx_banked.c"

bank1 {
#include "example_dobkeratops_tail.c"
// Generated by 
// rustc misc/dobkeratops_tail.rs -o dokeratops_tail
// ./dobkeratops_tail > examples/example_dobkeratops_tail.c
const char dobkeratops_x[] = {0, 0, 6, 6, 37, 35, 37, 37, 40, 25, 0};
const char dobkeratops_y[] = {0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160};
const char dobkeratops_nbbytes[] = {32, 32, 24, 32, 16, 19, 18, 19, 17, 19, 28};
const char *dobkeratops_gfx[] = {dob1, dob2, dob3, dob4, dob5, dob6, dob7, dob8, dob9, dob10, dob11};

void draw_dobkeratops(char xpos, char ypos, char anim)
{
    char x, y, c, *gfx;
    char *tailx = dobkeratops_tail_x[X = anim];
    char *taily = dobkeratops_tail_y[X];
    char margin = 16 - 12;
    // Draw tail
    gfx = tail1;
    for (c = 0; c != 17; c++) {
        x = tailx[Y = c] + xpos - 46;
        y = taily[Y] + ypos;
        if (c == 6) {
            gfx = tail2;
            margin = 16 - 10;
        } else if (c == 12) gfx = tail3;
        multisprite_display_small_sprite_ex(x, y, gfx, 2, 4, margin, 0);
    }
    x = tailx[Y = c] + xpos - 46;
    y = taily[Y] + ypos;
    multisprite_display_sprite_ex(x, y, tail4, 4, 4, 1);
    // Draw ugly alien body
    for (c = 0; c != 11; c++) {
        x = dobkeratops_x[X = c] + xpos;
        y = dobkeratops_y[X] + ypos;
        gfx = dobkeratops_gfx[X];
        // Move gfx reference to RAM
        gfx &= 0x0fff; // Keep lower 4kb bits
        gfx |= 0x7000; // dobkeratops_ram
        char nbbytes = dobkeratops_nbbytes[X];
        multisprite_display_sprite_aligned(x, y, gfx, nbbytes, 4, 1);
    }
}
} // bank1

bank2 void copy_dobkeratops_to_ram()
{
    char *dest = dobkeratops_ram, *src = dob1;
    for (X = 15; X >= 0; X--) {
        for (Y = 255; Y != 0; Y--) {
            dest[Y] = src[Y];
        }
        dest[Y] = src[Y];
        dest += 256;
        src += 256;
    }
}
